import os
from tinkoff.invest.constants import INVEST_GRPC_API, INVEST_GRPC_API_SANDBOX

IS_PROD = os.getenv("GRPC_PRODUCTION")
TOKEN = 't.rF5TUCVfJDhAdPFr-3qC08PFcQt4c1LCdjZw0bcTaGoivfyvSSQG5mZpurrCCwxfzv8Gv7ZMKUxuXm7IV0zYRA'
BOT_TOKEN = '1589984288:AAHTMIEZSXloP52SefpKGOijrEU198dt_y8'
ROOT_ID = "263948818"
TARGET = INVEST_GRPC_API if IS_PROD else INVEST_GRPC_API_SANDBOX
# TARGET = INVEST_GRPC_API
