import os
from tinkoff.invest.constants import INVEST_GRPC_API, INVEST_GRPC_API_SANDBOX

IS_PROD = os.getenv("GRPC_PRODUCTION")
TOKEN = os.getenv("TINKOFF_TOKEN")
BOT_TOKEN = os.getenv("TINKOFF_TG_BOT_TOKEN")
ROOT_ID = os.getenv("TINKIFF_ROOT_TG_ID")
TARGET = INVEST_GRPC_API if IS_PROD else INVEST_GRPC_API_SANDBOX
